<?php

namespace Database\Seeders;

use App\Models\Section;
use Illuminate\Database\Seeder;

class SectionSeeder extends Seeder
{
    public function run(): void
    {
        $sections = [
            [
                'key' => 'hero',
                'title' => 'Tech Sewing Machine',
                'subtitle' => 'Giải pháp may mặc công nghiệp',
                'content' => 'Cung cấp máy may công nghiệp, tư vấn dây chuyền, demo và hỗ trợ kỹ thuật cho xưởng may.',
                'image' => 'assets/frontend/images/anh1.jpg',
                'type' => 'hero',
                'is_active' => true,
                'sort_order' => 1,
                'container_class' => 'v-hero-premium section-shell-sm v-hero-image-only',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => 'pt-0',
                'spacing_bottom' => 'pb-0',
                'style_config' => [
                    'button_text' => 'Nhận tư vấn ngay',
                    'button_url' => '/lien-he',
                ],
            ],
            [
                'key' => 'strip',
                'title' => 'Số liệu nhanh',
                'subtitle' => 'Điểm nhấn trên trang chủ',
                'content' => 'Tổng hợp nhanh sản phẩm, danh mục và bài viết mới.',
                'image' => null,
                'type' => 'stats',
                'is_active' => true,
                'sort_order' => 2,
                'container_class' => 'v-home-strip section-shell-sm',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [
                    'item_1_title' => 'Danh mục nổi bật',
                    'item_1_subtitle' => 'mẫu máy tiêu biểu',
                    'item_2_title' => 'Nhóm sản phẩm',
                    'item_2_subtitle' => 'nhóm máy chủ lực',
                    'item_3_title' => 'Nội dung mới',
                    'item_3_subtitle' => 'bài viết cập nhật',
                    'item_4_title' => 'Chuyển đổi',
                    'item_4_subtitle' => 'Tìm kiếm, liên hệ và báo giá',
                ],
            ],
            [
                'key' => 'product-showcase',
                'title' => 'Sản phẩm nổi bật',
                'subtitle' => 'Trưng bày sản phẩm',
                'content' => 'Danh sách sản phẩm nổi bật, tập trung CTA và thông số quan trọng.',
                'image' => null,
                'type' => 'product',
                'is_active' => true,
                'sort_order' => 3,
                'container_class' => 'v-content-wrap v-content-white section-shell',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [],
            ],
            [
                'key' => 'value-section',
                'title' => 'Giá trị thương hiệu',
                'subtitle' => 'Giá trị',
                'content' => 'Tập trung SEO, conversion flow và trải nghiệm tư vấn cho khách hàng B2B.',
                'image' => 'assets/frontend/images/anh2.jpg',
                'type' => 'content',
                'is_active' => true,
                'sort_order' => 4,
                'container_class' => 'v-z-section section-shell v-z-section-featured',
                'bg_color' => '#0b1220',
                'text_color' => '#ffffff',
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [
                    'feature_1_title' => 'SEO first',
                    'feature_1_desc' => 'Meta, canonical, schema và URL nhất quán.',
                    'feature_2_title' => 'Conversion flow',
                    'feature_2_desc' => 'CTA, form liên hệ và hành trình sản phẩm rõ ràng.',
                    'feature_3_title' => 'Content-driven',
                    'feature_3_desc' => 'Sản phẩm và bài viết là trung tâm tăng trưởng.',
                    'button_text' => 'Xem câu chuyện thương hiệu',
                    'button_url' => '/gioi-thieu',
                ],
            ],
            [
                'key' => 'tool-section',
                'title' => 'Hỗ trợ triển khai và bảo trì',
                'subtitle' => 'Công cụ tư vấn',
                'content' => 'Tư vấn dòng máy, cấu hình dây chuyền, hướng dẫn kỹ thuật và chăm sóc sau bán hàng.',
                'image' => 'assets/frontend/images/anh3.jpg',
                'type' => 'content',
                'is_active' => true,
                'sort_order' => 5,
                'container_class' => 'v-z-section reverse section-shell v-z-section-featured',
                'bg_color' => '#ffffff',
                'text_color' => '#0b1220',
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [
                    'metric_1_value' => '24h',
                    'metric_1_label' => 'Tiếp nhận yêu cầu ưu tiên',
                    'metric_2_value' => '100+',
                    'metric_2_label' => 'Mô hình xưởng có thể áp dụng',
                    'metric_3_value' => '63',
                    'metric_3_label' => 'Tỉnh thành hỗ trợ',
                    'metric_4_value' => '10 năm',
                    'metric_4_label' => 'Định hướng dịch vụ dài hạn',
                    'button_text' => 'Nhận tư vấn triển khai',
                    'button_url' => '/lien-he',
                ],
            ],
            [
                'key' => 'content-hub',
                'title' => 'Sản phẩm mới và nội dung mới nhất',
                'subtitle' => 'Trung tâm nội dung',
                'content' => 'Trang chủ như một hub: danh mục, sản phẩm, bài viết và đối tác.',
                'image' => null,
                'type' => 'content',
                'is_active' => true,
                'sort_order' => 6,
                'container_class' => 'v-content-wrap v-content-white section-shell',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [
                    'left_title' => 'Mẫu mới nhất',
                    'left_link_text' => 'Xem toàn bộ',
                    'right_title' => 'Tin tức mới',
                    'right_link_text' => 'Xem tin tức',
                ],
            ],
            [
                'key' => 'partners',
                'title' => 'Đối tác',
                'subtitle' => 'Thương hiệu đồng hành',
                'content' => 'Các thương hiệu và đối tác cung cấp thiết bị, linh kiện liên quan.',
                'image' => null,
                'type' => 'logo',
                'is_active' => true,
                'sort_order' => 7,
                'container_class' => 'v-partner-strip section-shell',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [],
            ],
            [
                'key' => 'cta',
                'title' => 'Sẵn sàng nâng cấp dây chuyền may?',
                'subtitle' => 'Kêu gọi hành động',
                'content' => 'Để lại nhu cầu: loại hàng, năng suất, ngân sách. Kỹ thuật sẽ tư vấn cấu hình phù hợp.',
                'image' => 'assets/frontend/images/anh6.jpg',
                'type' => 'cta',
                'is_active' => true,
                'sort_order' => 8,
                'container_class' => 'v-parallax-wrapper section-shell',
                'bg_color' => null,
                'text_color' => null,
                'spacing_top' => null,
                'spacing_bottom' => null,
                'style_config' => [
                    'button_text' => 'Gửi yêu cầu ngay',
                    'button_url' => '/lien-he',
                ],
            ],
        ];

        foreach ($sections as $section) {
            Section::firstOrCreate(['key' => $section['key']], $section);
        }
    }
}

